apiVersion: v1
kind: ServiceAccount
metadata:
  name: hybrid-scheduler-admission
  namespace: keti-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hybrid-scheduler-admission
  namespace: keti-system
subjects:
- kind: ServiceAccount
  name: hybrid-scheduler-admission
  namespace: keti-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hybrid-scheduler-admission-create
  namespace: keti-system
spec:
  template:
    metadata:
      name: hybrid-scheduler-admission-create
      namespace: keti-system
    spec:
      imagePullSecrets: 
      - name: ketidevit2
      containers:
        - name: create
          image: docker.io/jettech/kube-webhook-certgen:v1.5.2
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --cert-name=tls.crt
            - --key-name=tls.key
            - --host="hybrid-scheduler.keti-system.svc,127.0.0.1"
            - --namespace=keti-system
            - --secret-name=hybrid-scheduler-tls
      restartPolicy: OnFailure
      serviceAccountName: hybrid-scheduler-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
