apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeploy
  namespace: openmcp2
spec:
  replicas: 30
  labels:
      app: openmcp-nginx
      test: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - image: nginx
            name: nginx
#            resources:
#              requests:
#                memory: "100"
#                cpu: "0.1"
