apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: example-openmcpdeployment-default
  namespace: openmcp
spec:
  replicas: 5
  clusters:
  - "cluster1"
  - "cluster2"

  labels:
      app: openmcp-nginx
      test: "yes"
  template:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: regcred        
          containers:
          - image: nginx
            name: nginx
            resources:
              requests:
                memory: "100"
                cpu: "1"
