#NodeResourceFit: 파드의 요청 자원 확인
apiVersion: v1
kind: Pod
metadata:
  name: keti-application15
  annotation: 
    schedulepolicy: noderesourcefit
  labels:
    name: keti-application15
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application15
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name