#BalanceAllocation: 노드의 자원 사용량 균형을 위한 pod 배치
apiVersion: v1
kind: Pod
metadata:
  name: keti-application19
  annotations: 
    schedulepolicy: balanceallocation
  labels:
    name: keti-application19
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application19
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1