#VolumeBinding: 노드에 따른 volume binding 유무 확인
apiVersion: v1
kind: Pod
metadata:
  name: keti-application17
  annotations: 
    schedulepolicy: volumebinding
  labels:
    name: keti-application17
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application17
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1