#NodePorts: 요청된 파드 포트에 대한 사용유무 확인
apiVersion: v1
kind: Pod
metadata:
  name: keti-application7
  annotations: 
    schedulepolicy: nodeports
  labels:
    name: keti-application7
spec:
  hostNetwork: true
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application7
    image: ketidevit2/keti-application:latest
    ports:
    - containerPort: 32147
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1