#SelectSpread: 동일한 속성을 가지는 클러스터 선택
apiVersion: v1
kind: Pod
metadata:
  name: keti-application14
  annotations: 
    schedulepolicy: selectspread
  labels:
    name: keti-application14
    kind: deployment
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application14
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1