#TaintToleration: 노드의 taint 및 toleration 확인
apiVersion: v1
kind: Pod
metadata:
  name: keti-application16
  annotations: 
    schedulepolicy: tainttoleration
  labels:
    name: keti-application16
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application16
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1