#OptimizationCount: Resource Optimization 횟수가 적은 노드 선택
apiVersion: v1
kind: Pod
metadata:
  name: keti-application3
  annotation: 
    schedulepolicy: optimizationcount
  labels:
    name: keti-application3
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application3
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name