#Affinity: 노드의 친밀도 확인
apiVersion: v1
kind: Pod
metadata:
  name: keti-application4
  annotation: 
    schedulepolicy: affinity
  labels:
    name: keti-application4
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application4
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name