#NodeUnschedulable: 파드의 스케줄링 enable 확인
apiVersion: v1
kind: Pod
metadata:
  name: keti-application8
  annotations: 
    schedulepolicy: nodeunschedulable
  labels:
    name: keti-application8
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application8
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1