#NodePreferAvoidPods: Annotation에 따른 점수 기반으로 노드 선택
apiVersion: v1
kind: Pod
metadata:
  name: keti-application13
  annotations: 
    schedulepolicy: nodepreferavoidpods
  labels:
    name: keti-application13
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application13
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1