#NodeRegion: 동일 Pod가 한 클라우드 내에 있을 경우 가장 먼 Region/Zone 노드 선택
apiVersion: v1
kind: Pod
metadata:
  name: keti-application2
  annotation: 
    schedulepolicy: noderegion
  labels:
    name: keti-application2
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application2
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name