#LocationAffinity: 클라우드 서버의 위치 기반으로 선택
apiVersion: v1
kind: Pod
metadata:
  name: keti-application5
  annotations: 
    schedulepolicy: locationaffinity
    zone: korea
    region: asia
  labels:
    name: keti-application5
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application5
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1