#OptimizationTime: 마지막 Resource Optimization 완료 시간이 가장 최신 노드 선택
apiVersion: v1
kind: Pod
metadata:
  name: keti-application12
  annotations: 
    schedulepolicy: optimizationtime
  labels:
    name: keti-application12
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application12
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      limits:
        keti.hybrid/schedule: 1