#NodeName: 파드 명세에 정의된 노드 이름과 현재 노드 일치 확인
apiVersion: v1
kind: Pod
metadata:
  name: keti-application6
  annotation: 
    schedulepolicy: nodename
  labels:
    name: keti-application6
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application6
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name