#ImageLocality: 동일 파드의 이미지 유무 기반 노드 선택
apiVersion: v1
kind: Pod
metadata:
  name: keti-application11
  annotation: 
    schedulepolicy: imagelocality
  labels:
    name: keti-application11
spec:
  imagePullSecrets: 
  - name: ketidevit2
  restartPolicy: Always
  containers:
  - name: keti-application11
    image: ketidevit2/keti-application:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name